//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PessoaBackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        public long nr_cpf { get; set; }
        public string ds_nome { get; set; }
        public string ds_sobrenome { get; set; }
        public string ds_nacionalidade { get; set; }
        public string nr_cep { get; set; }
        public string ds_estado { get; set; }
        public string ds_cidade { get; set; }
        public string ds_logradouro { get; set; }
        public string ds_email { get; set; }
        public string nr_telefone { get; set; }
    }
}
